version: "3.7"
services:
  pypublish:
    build: ./PYPublish/
    depends_on:
      - mqtt5Mongodb
  pysubscribe:
    build: ./PYSubscribe/
    depends_on:
      - mqtt5Mongodb
  pymonitor:
    build: ./PYMonitor/
    depends_on:
      - mqtt5Mongodb
  mqtt5Mongodb:
    image: eclipse-mosquitto
    container_name: mqtt5Mongodb
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./MqttMongodb/config:/mosquitto/config:rw
      - ./MqttMongodb/data:/mosquitto/data:rw
      - ./MqttMongodb/log:/mosquitto/log:rw

  mqtt5Monitor:
    image: eclipse-mosquitto
    container_name: mqtt5Monitor
    ports:
      - "1884:1884" #default mqtt port
      - "9002:9002" #default mqtt port for websockets
    volumes:
      - ./MqttMonitor/config:/mosquitto/config:rw
      - ./MqttMonitor/data:/mosquitto/data:rw
      - ./MqttMonitor/log:/mosquitto/log:rw    

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:
